### ISSUE TITLE
Akamai Sandbox throws an error - Error loading shared library ld-linux-x86-64.so.2

### ISSUE THREAD

**Issue by lukaszczerpak** [lukaszczerpak/akamai-devops-docker#1]
```
Akamai DevOps [~] >> akamai sandbox start no sandbox client installed. Installing sandbox client...
downloading sandbox client...
installing to /cli/.akamai-cli/cache/sandbox-cli/sandbox-client-1.2.0-RELEASE
done
launching client with command: "/usr/lib/jvm/default-jvm/bin/java" -Dlogging.path="/cli/.akamai-cli/cache/sandbox-cli/sandboxes/code2/logs" -Dlogging.config="/cli/.akamai-cli/cache/sandbox-cli/sandbox-client-1.2.0-RELEASE/conf/logback.xml" -jar "/cli/.akamai-cli/cache/sandbox-cli/sandbox-client-1.2.0-RELEASE/lib/sandbox-client-1.2.0-RELEASE.jar" --config="/cli/.akamai-cli/cache/sandbox-cli/sandboxes/code2/config.json"
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libconscrypt_openjdk_jni-linux-x86_6415677306633460000.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/libconscrypt_openjdk_jni-linux-x86_6415677306633460000.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:52)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.conscrypt.NativeLibraryLoader$1.run(NativeLibraryLoader.java:297)
        at org.conscrypt.NativeLibraryLoader$1.run(NativeLibraryLoader.java:289)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.conscrypt.NativeLibraryLoader.loadLibraryFromHelperClassloader(NativeLibraryLoader.java:289)
        at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:262)
        at org.conscrypt.NativeLibraryLoader.loadFromWorkdir(NativeLibraryLoader.java:201)
        at org.conscrypt.NativeLibraryLoader.load(NativeLibraryLoader.java:162)
        at org.conscrypt.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:106)
        at org.conscrypt.NativeCryptoJni.init(NativeCryptoJni.java:50)
        at org.conscrypt.NativeCrypto.<clinit>(NativeCrypto.java:65)
        at org.conscrypt.OpenSSLProvider.<init>(OpenSSLProvider.java:60)
        at org.conscrypt.OpenSSLProvider.<init>(OpenSSLProvider.java:53)
        at org.conscrypt.OpenSSLProvider.<init>(OpenSSLProvider.java:49)
        at com.akamai.devpops.connector.ConnectorMain.main(ConnectorMain.java:84)
        ... 8 more
        Suppressed: java.lang.UnsatisfiedLinkError: /tmp/libconscrypt_openjdk_jni-linux-x86_6415677306633460000.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/libconscrypt_openjdk_jni-linux-x86_6415677306633460000.so)
                at java.lang.ClassLoader$NativeLibrary.load(Native Method)
                at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
                at java.lang.Runtime.load0(Runtime.java:809)
                at java.lang.System.load(System.java:1086)
                at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:52)
                at org.conscrypt.NativeLibraryLoader.loadLibraryFromCurrentClassloader(NativeLibraryLoader.java:318)
                at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:273)
                ... 17 more
        Suppressed: java.lang.UnsatisfiedLinkError: no conscrypt_openjdk_jni-linux-x86_64 in java.library.path
                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
                at java.lang.Runtime.loadLibrary0(Runtime.java:870)
                at java.lang.System.loadLibrary(System.java:1122)
                at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:54)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.conscrypt.NativeLibraryLoader$1.run(NativeLibraryLoader.java:297)
                at org.conscrypt.NativeLibraryLoader$1.run(NativeLibraryLoader.java:289)
                at java.security.AccessController.doPrivileged(Native Method)
                at org.conscrypt.NativeLibraryLoader.loadLibraryFromHelperClassloader(NativeLibraryLoader.java:289)
                at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:262)
                ... 16 more
        Suppressed: java.lang.UnsatisfiedLinkError: no conscrypt_openjdk_jni-linux-x86_64 in java.library.path
                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
                at java.lang.Runtime.loadLibrary0(Runtime.java:870)
                at java.lang.System.loadLibrary(System.java:1122)
                at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:54)
                at org.conscrypt.NativeLibraryLoader.loadLibraryFromCurrentClassloader(NativeLibraryLoader.java:318)
                at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:273)
                ... 16 more
        Suppressed: java.lang.UnsatisfiedLinkError: no conscrypt_openjdk_jni in java.library.path
                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
                at java.lang.Runtime.loadLibrary0(Runtime.java:870)
                at java.lang.System.loadLibrary(System.java:1122)
                at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:54)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.conscrypt.NativeLibraryLoader$1.run(NativeLibraryLoader.java:297)
                at org.conscrypt.NativeLibraryLoader$1.run(NativeLibraryLoader.java:289)
                at java.security.AccessController.doPrivileged(Native Method)
                at org.conscrypt.NativeLibraryLoader.loadLibraryFromHelperClassloader(NativeLibraryLoader.java:289)
                at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:262)
                ... 16 more
        Suppressed: java.lang.UnsatisfiedLinkError: no conscrypt_openjdk_jni in java.library.path
                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
                at java.lang.Runtime.loadLibrary0(Runtime.java:870)
                at java.lang.System.loadLibrary(System.java:1122)
                at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:54)
                at org.conscrypt.NativeLibraryLoader.loadLibraryFromCurrentClassloader(NativeLibraryLoader.java:318)
                at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:273)
                ... 16 more
        Suppressed: java.lang.UnsatisfiedLinkError: no conscrypt in java.library.path
                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
                at java.lang.Runtime.loadLibrary0(Runtime.java:870)
                at java.lang.System.loadLibrary(System.java:1122)
                at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:54)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.conscrypt.NativeLibraryLoader$1.run(NativeLibraryLoader.java:297)
                at org.conscrypt.NativeLibraryLoader$1.run(NativeLibraryLoader.java:289)
                at java.security.AccessController.doPrivileged(Native Method)
                at org.conscrypt.NativeLibraryLoader.loadLibraryFromHelperClassloader(NativeLibraryLoader.java:289)
                at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:262)
                ... 16 more
        Suppressed: java.lang.UnsatisfiedLinkError: no conscrypt in java.library.path
                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
                at java.lang.Runtime.loadLibrary0(Runtime.java:870)
                at java.lang.System.loadLibrary(System.java:1122)
                at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:54)
                at org.conscrypt.NativeLibraryLoader.loadLibraryFromCurrentClassloader(NativeLibraryLoader.java:318)
                at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:273)
                ... 16 more
exec: Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libconscrypt_openjdk_jni-linux-x86_6415677306633460000.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/libconscrypt_openjdk_jni-linux-x86_6415677306633460000.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:52)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.conscrypt.NativeLibraryLoader$1.run(NativeLibraryLoader.java:297)
        at org.conscrypt.NativeLibraryLoader$1.run(NativeLibraryLoader.java:289)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.conscrypt.NativeLibraryLoader.loadLibraryFromHelperClassloader(NativeLibraryLoader.java:289)
        at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:262)
        at org.conscrypt.NativeLibraryLoader.loadFromWorkdir(NativeLibraryLoader.java:201)
        at org.conscrypt.NativeLibraryLoader.load(NativeLibraryLoader.java:162)
        at org.conscrypt.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:106)
        at org.conscrypt.NativeCryptoJni.init(NativeCryptoJni.java:50)
        at org.conscrypt.NativeCrypto.<clinit>(NativeCrypto.java:65)
        at org.conscrypt.OpenSSLProvider.<init>(OpenSSLProvider.java:60)
        at org.conscrypt.OpenSSLProvider.<init>(OpenSSLProvider.java:53)
        at org.conscrypt.OpenSSLProvider.<init>(OpenSSLProvider.java:49)
        at com.akamai.devpops.connector.ConnectorMain.main(ConnectorMain.java:84)
        ... 8 more
        Suppressed: java.lang.UnsatisfiedLinkError: /tmp/libconscrypt_openjdk_jni-linux-x86_6415677306633460000.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/libconscrypt_openjdk_jni-linux-x86_6415677306633460000.so)
                at java.lang.ClassLoader$NativeLibrary.load(Native Method)
                at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
                at java.lang.Runtime.load0(Runtime.java:809)
                at java.lang.System.load(System.java:1086)
                at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:52)
                at org.conscrypt.NativeLibraryLoader.loadLibraryFromCurrentClassloader(NativeLibraryLoader.java:318)
                at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:273)
                ... 17 more
        Suppressed: java.lang.UnsatisfiedLinkError: no conscrypt_openjdk_jni-linux-x86_64 in java.library.path
                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
                at java.lang.Runtime.loadLibrary0(Runtime.java:870)
                at java.lang.System.loadLibrary(System.java:1122)
                at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:54)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.conscrypt.NativeLibraryLoader$1.run(NativeLibraryLoader.java:297)
                at org.conscrypt.NativeLibraryLoader$1.run(NativeLibraryLoader.java:289)
                at java.security.AccessController.doPrivileged(Native Method)
                at org.conscrypt.NativeLibraryLoader.loadLibraryFromHelperClassloader(NativeLibraryLoader.java:289)
                at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:262)
                ... 16 more
        Suppressed: java.lang.UnsatisfiedLinkError: no conscrypt_openjdk_jni-linux-x86_64 in java.library.path
                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
                at java.lang.Runtime.loadLibrary0(Runtime.java:870)
                at java.lang.System.loadLibrary(System.java:1122)
                at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:54)
                at org.conscrypt.NativeLibraryLoader.loadLibraryFromCurrentClassloader(NativeLibraryLoader.java:318)
                at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:273)
                ... 16 more
        Suppressed: java.lang.UnsatisfiedLinkError: no conscrypt_openjdk_jni in java.library.path
                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
                at java.lang.Runtime.loadLibrary0(Runtime.java:870)
                at java.lang.System.loadLibrary(System.java:1122)
                at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:54)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.conscrypt.NativeLibraryLoader$1.run(NativeLibraryLoader.java:297)
                at org.conscrypt.NativeLibraryLoader$1.run(NativeLibraryLoader.java:289)
                at java.security.AccessController.doPrivileged(Native Method)
                at org.conscrypt.NativeLibraryLoader.loadLibraryFromHelperClassloader(NativeLibraryLoader.java:289)
                at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:262)
                ... 16 more
        Suppressed: java.lang.UnsatisfiedLinkError: no conscrypt_openjdk_jni in java.library.path
                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
                at java.lang.Runtime.loadLibrary0(Runtime.java:870)
                at java.lang.System.loadLibrary(System.java:1122)
                at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:54)
                at org.conscrypt.NativeLibraryLoader.loadLibraryFromCurrentClassloader(NativeLibraryLoader.java:318)
                at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:273)
                ... 16 more
        Suppressed: java.lang.UnsatisfiedLinkError: no conscrypt in java.library.path
                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
                at java.lang.Runtime.loadLibrary0(Runtime.java:870)
                at java.lang.System.loadLibrary(System.java:1122)
                at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:54)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.conscrypt.NativeLibraryLoader$1.run(NativeLibraryLoader.java:297)
                at org.conscrypt.NativeLibraryLoader$1.run(NativeLibraryLoader.java:289)
                at java.security.AccessController.doPrivileged(Native Method)
                at org.conscrypt.NativeLibraryLoader.loadLibraryFromHelperClassloader(NativeLibraryLoader.java:289)
                at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:262)
                ... 16 more
        Suppressed: java.lang.UnsatisfiedLinkError: no conscrypt in java.library.path
                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
                at java.lang.Runtime.loadLibrary0(Runtime.java:870)
                at java.lang.System.loadLibrary(System.java:1122)
                at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:54)
                at org.conscrypt.NativeLibraryLoader.loadLibraryFromCurrentClassloader(NativeLibraryLoader.java:318)
                at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:273)
                ... 16 more

```

**Comment by lukaszczerpak** [comment]
This is due to a missing `gcompat` package
